#pragma once

#include <godot_cpp/godot.hpp>
#define GDXMOD_LIBRARY_INITIALIZE_FUNC initialize_##_GDXMOD_LIB_NAME##_types
#define GDXMOD_LIBRARY_UNINITIALIZE_FUNC uninitialize_##_GDXMOD_LIB_NAME##_types
#define GDXMOD_LIBRARY_INITIALIZE_NAME GDXMOD_LIBRARY_INITIALIZE_FUNC(godot::ModuleInitializationLevel p_level)
#define GDXMOD_LIBRARY_UNINITIALIZE_NAME GDXMOD_LIBRARY_UNINITIALIZE_FUNC(godot::ModuleInitializationLevel p_level)

void GDXMOD_LIBRARY_INITIALIZE_NAME;
void GDXMOD_LIBRARY_UNINITIALIZE_NAME;